title: "EditorConfig"
description: "EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs."
url: https://editorconfig.org
permalink: pretty
exclude: [ 'ReadMe.md' ]
